[programs.localnet]
solana_svelte_counter = "Ae2J3Cn2Vtrm4jc9dJiWtBZ16Pxd5xTtFNGAhKT2Djwm"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "/Users/silvestrevivo/.config/solana/id.json"

[scripts]
test = "mocha -t 1000000 tests/"
