[programs.devnet]
solana_svelte_counter = "C7SGr2s3HdBuEveTahL9H3CsXQDwxkYEUSRPeJAVeDN5"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "/Users/silvestrevivo/.config/solana/id.json"

[scripts]
test = "mocha -t 1000000 tests/"
